version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"        # Puerto de RabbitMQ
      - "15672:15672"      # Puerto de la interfaz de administración
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "8080:8080"        # Puerto de tu aplicación
    networks:
      - mynetwork
    depends_on:
      - rabbitmq

networks:
  mynetwork:
    driver: bridge
